config/routes.rb
Demandi::Application.routes.draw do
  devise_for :users

  resources :questions do
    resources :answers
  end

  resources :answers, only: [:show] do
    resources :comments
  end

  root 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates_presence_of :body, :user_id, :question_id
  validates_length_of :body, maximum: 1000

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :answer
  belongs_to :user

  validates_presence_of :body, :user_id, :answer_id
  validates_length_of :body, maximum: 1000
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  belongs_to :user

  scope :desc_order, -> {order('created_at DESC') }

  validates_presence_of :title, :body, :user_id
  validates_length_of :body, maximum: 1000
  validates_length_of :title, maximum: 100
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(answer_params)

    if @answer.save
      flash[:succes] = 'Your answer has been submited.'
      redirect_to @question
    else
      @question = Question.find(params[:question_id])
      render 'questions/show'
    end
  end

  private

    def answer_params
      params.require(:answer).permit(:body, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :user_name
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, :set_answer

  def create
    @comment = @answer.comments.build(comments_params)

    if @comment.save
      flash[:succes] = 'Your comment was submitted'
      redirect_to :back
    else
      flash[:error] = 'Your comment was not submitted'
      redirect_to :back
    end

  end

  def new
    @comment = Comment.new
    @parent = Comment.find(params[:comment_id]) if params[:comment_id]

    respond_to do |format|
      format.js
    end
  end

  private

    def comments_params
      params.require(:comment).permit(:body, :answer_id, :l_margin, :user_id, :parent_id)
    end

    def set_answer
      @answer = Answer.find(params[:answer_id])
    end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @questions = Question.includes(:user, :answers).desc_order.paginate(page: params[:page], per_page: 5)
    @question = Question.new
  end

  def create
    @question = current_user.questions.build(question_params)

    if @question.save
      flash[:success] = 'Your question was posted.'
      redirect_to @question
    else
      @questions = Question.all.desc_order.paginate(page: params[:page], per_page: 5)
      render 'index'
    end
  end

  def show
    @question = Question.includes(answers: [:comments, :user]).find(params[:id])
    @answer = Answer.new
    @comment = Comment.new
  end

  private

    def question_params
      params.require(:question).permit(:title, :body, :user_id)
    end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = 'Demandi'
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper

  def show_reply(comments, comment, &blk)
    blk.call(comment)

    if comments[comment.id]
      comments[comment.id].each do |re|
        show_reply(comments, re, &blk)
      end
    else
      return
    end

  end

  def get_comments_for(answer)
    answer.comments.group_by(&:parent_id)
  end

  def render_comments_for(answer, &blk)
    comments = get_comments_for(answer)

    unless comments.empty?
      comments[0].each do |comment|
        show_reply(comments, comment, &blk)
      end
    end
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.haml
.answer
  .answer-date
    = answer.created_at.to_formatted_s(:long)
    by
    %span.user-name
      = answer.user.user_name
  .answer-body
    %div
      %p
        = answer.body
        = link_to 'leave comment', new_answer_comment_path(answer), class: 'comment-link', remote: true
      - if answer.comments.any?
        %span.hide-comments
          %i.icon-chevron-down
          comments
        .comments
          - render_comments_for(answer) do |comment|
            .comment{ style: "margin-left: #{comment.l_margin}px" }
              %p.comment-content
                = comment.body
              = link_to 'reply', new_answer_comment_path(answer,comment_id: comment.id), class: 'comment-link', remote: true

app/views/answers/_answer_form.html.haml
%h3 Post answer to this question
.full-question-info
= simple_form_for( [@question,@answer], html: { class: 'form-horizontal' } ) do |f|
  = f.hidden_field :user_id, value: current_user.id
  = f.input :body, input_html: { class: 'span5', rows: '5' }, label: false
  .control-group
    .controls
      = f.button :submit, class: 'btn-primary'
      = submit_tag 'Cancel', type: :reset, class: 'btn btn-danger'
%hr

app/views/comments/_comment_form.html.haml
= simple_form_for( [answer, comment] , html: { class: 'form-horizontal' } ) do |f|
  = render 'shared/form_errors', object: f.object
  = f.hidden_field :parent_id, value: parent ? parent.id : 0
  = f.hidden_field :l_margin, value: parent ? parent.l_margin + 20 : 0
  = f.hidden_field :user_id, value: current_user.id
  = f.input :body, input_html: { class: 'span5', rows: '5' }, label: false
  .control-group
    .controls
      = f.button :submit, class: 'btn-primary'
      = submit_tag 'Cancel', type: :reset, class: 'btn btn-danger discard'

app/views/comments/new.js.erb
comment_form = $('.comment-form').css('display', 'none')
comment_form.append("<%= escape_javascript render partial: 'comments/comment_form', locals: { answer: @answer, comment: @comment, parent: @parent } %>")
comment_form.slideDown('200');

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      = full_title(yield(:title))
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .container
      .navbar.navbar-fixed-top.navbar-inverse
        .navbar-inner
          %ul.nav.pull-right
            - if current_user
              %li
                = link_to 'Home', root_path
              %li
                = link_to 'Sign out', destroy_user_session_path, method: :delete
            - else
              %li
                = link_to 'Sign up', new_user_registration_path
              %li
                = link_to 'Sign in', new_user_session_path
      - flash.each do |key, value|
        = content_tag(:div, value, class: "alert alert-#{key}")
      = yield
      = debug(params) if Rails.env.development?

app/views/questions/_question.html.haml
.question
  .question-title
    = link_to truncate(question.title, length: 100), question
  .question-info
    = pluralize(question.answers.length, 'answer')
  .question-body
    = truncate(question.body, length: 30)
  .question-date
    %span
      posted on:
      = question.created_at.to_formatted_s(:long)
      by
      %span.user-name
        = question.user.user_name

app/views/questions/_question_form.html.haml
%h1 Questions ?
%hr
= simple_form_for( @question, html: { class: 'form-horizontal' } ) do |f|
  = f.input :title, wrapper: :prepend, label: false do
    = content_tag :span, 'Title', class: 'add-on'
    = f.input_field :title
  = f.input :body, input_html: { class: 'span5', rows: '5' }, label: false
  .control-group
    .controls
      = f.button :submit, class: 'btn-primary'
      = submit_tag 'Cancel', type: :reset, class: 'btn btn-danger'
%hr

app/views/questions/index.html.haml
.row
  .span8
    .question-form
      = render 'question_form'
    .row
      .span7
        .question-list
          %h2 List of all questions
          - if @questions.any?
            = render @questions
          - else
            .block-notice
              No questions have been posted yet.
          = will_paginate @questions

app/views/questions/show.html.haml
.row
  .span10
    .full-question
      %h2
        = @question.title
      .date
        = @question.created_at.to_formatted_s(:long)
      .question-body
        = @question.body
      .question-author
        posted by -
        = @question.user.user_name

      .answer-form
        = render 'answers/answer_form'

      %div
        - if @question.answers.any?
          .answers
            = render @question.answers
        - else
          .block-notice
            Noone has answered this question yet.

app/views/shared/_form_errors.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-error The form contains #{pluralize(object.errors.count, 'error')}
    %ul
      - object.errors.full_messages.each do |msg|
        %li
          = msg